/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Window;

import DateBase.JDBC;
import File.FileTypeFilter;
import java.io.File;
import javax.swing.*;

/**
 *
 * @author kamil
 */
public class Menu_win extends JFrame
{
    
    public String GetNameClass()
    {
        return "Menu_win";
    }
    
    public Menu_win()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Search = new javax.swing.JButton();
        Library = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Export = new javax.swing.JMenuItem();
        Import = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(450, 300, 0, 0));

        Search.setText("Search ");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        Library.setText("Library");
        Library.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LibraryActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        Export.setText("Export");
        Export.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExportActionPerformed(evt);
            }
        });
        jMenu1.add(Export);

        Import.setText("Import");
        Import.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImportActionPerformed(evt);
            }
        });
        jMenu1.add(Import);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Library, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(Search)
                .addGap(18, 18, 18)
                .addComponent(Library)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        new Search_win(thisFrame).setVisible(true);
        thisFrame.setVisible(false);
    }//GEN-LAST:event_SearchActionPerformed

    private void LibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LibraryActionPerformed
        new Library_win(thisFrame).setVisible(true);
    }//GEN-LAST:event_LibraryActionPerformed

    private void ExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExportActionPerformed
        try 
        {
            JFileChooser jfileChooser = new JFileChooser("/Users/kamil/Desktop/Programowanie/Java/MovieApp");
            jfileChooser.setDialogTitle("Export Database to XML");
            jfileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
            jfileChooser.setSelectedFile(new File("Database_MovieApp.xml"));
            jfileChooser.setFileFilter(new FileTypeFilter(".xml", "XML File"));
            int result = jfileChooser.showSaveDialog(null);
            if(result == JFileChooser.APPROVE_OPTION)
            {
                xmlFile = jfileChooser.getSelectedFile().getAbsolutePath();
            }
            JDBC jdbc = new JDBC("export");
            JOptionPane.showMessageDialog(null, "File export successfully!");

        } 
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(null, "Can't select XML file");
        }
    }//GEN-LAST:event_ExportActionPerformed

    private void ImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImportActionPerformed
        try 
        {
            JFileChooser jfileChooser = new JFileChooser("/Users/kamil/Desktop/Programowanie/Java/MovieApp");
            jfileChooser.setDialogTitle("Please select XML file");
            jfileChooser.setFileFilter(new FileTypeFilter(".xml", "XML File"));
            int result = jfileChooser.showSaveDialog(null);
            if(result == JFileChooser.APPROVE_OPTION)
            {
                xmlFile = jfileChooser.getSelectedFile().getAbsolutePath();
            }
            JDBC jdbc = new JDBC("import");
            JOptionPane.showMessageDialog(null, "File import successfully!");
        } 
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(null, "Can't select XML file");
        }
    }//GEN-LAST:event_ImportActionPerformed

    public static String get_xmlFile()
    {
        return xmlFile;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_win.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_win.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_win.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_win.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_win().setVisible(true);
            }
        });
    }

    private static String xmlFile = "";
    private JFrame thisFrame = this;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Export;
    private javax.swing.JMenuItem Import;
    private javax.swing.JButton Library;
    private javax.swing.JButton Search;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
